### ISSUE TITLE
[RFC][Draft] CLI Input/Output interfaces

### ISSUE THREAD

**Issue by Addvilz** [php-cds/php-cds#19]
RFC draft for uniform IO interface. Because PHP folk also loves CLI tools. ❤️ 

This could help us bundle reusable command line libraries/tools/commands and share them around. Comments welcome.

``` php
interface InputInterface
{
    /**
     * Prompt user for input line.
     * @param string $prompt
     * @throws \RuntimeException when on non-interactive shell.
     * @return string
     */
    public function readLine($prompt);

    /**
     * Prompt user for confirmation (Y/N).
     * @param string $prompt
     * @throws \RuntimeException when on non-interactive shell.
     * @return bool
     */
    public function prompt($prompt);

    /**
     * Indicate that given input has interactive capabilities.
     * @param bool $interactive
     * @return $this
     */
    public function setInteractive($interactive);

    /**
     * Confirm that given input has interactive capabilities.
     * @return bool
     */
    public function isInteractive();

    /**
     * @param int|string $key
     * @param scalar $value
     * @return $this
     */
    public function setArgument($key, $value);

    /**
     * @param int|string $key
     * @return scalar
     */
    public function getArgument($key);

    /**
     * @param int|string $key
     * @return bool
     */
    public function hasArgument($key);

    /**
     * @return scalar[]
     */
    public function getArguments();

    /**
     * @param string $key
     * @param scalar $value
     * @return $this
     */
    public function setOption($key, $value);

    /**
     * @param string $key
     * @return scalar
     */
    public function getOption($key);

    /**
     * @param string $key
     * @return bool
     */
    public function hasOption($key);

    /**
     * @return scalar[]
     */
    public function getOptions();
}


interface OutputInterface
{
    /**
     * Write scalar value or object that can be cast to string to given output.
     * @param scalar|object
     * @return $this
     */
    public function write($message);

    /**
     * Write scalar value or object that can be cast to string to given output and append a newline.
     * @param scalar|object $message
     * @return $this
     */
    public function writeln($message);

    /**
     * Write scalar value or object that can be cast to string to given output and
     * indicating error output preference (for example, stderr).
     * @param scalar|object
     * @return $this
     */
    public function writeErr($message);

    /**
     * Write scalar value or object that can be cast to string to given output and append a newline
     * indicating error output preference (for example, stderr).
     * @param scalar|object $message
     * @return $this
     */
    public function writeErrln($message);

    /**
     * Confirm whether given output is capable of handling ANSI escape codes.
     * @return bool
     */
    public function isDecorated();

    /**
     * Indicate whether given output is capable of handling ANSI escape codes.
     * @param bool $decorated
     * @return $this
     */
    public function setDecorated($decorated);
}
```

Kudos to Symfony and others for inspiration. If you think you have seen this somewhere else before, you have. :)

All relevant discussion in discussion thread below! 👍

**Comment by samdark** [comment]
Do we really need to have `setArgument()` and `setOption()`? As far as I understand, these are read only once.

**Comment by Addvilz** [comment]
@samdark sorry, I don't understand your point. Could you elaborate?

**Comment by OddGreg** [comment]
Considering that these are interfaces to mutable objects, I can understand the value of `setArgument()` and `setOption()` methods rather than to assume that a constructor would require or embed optional dependencies. Or have I misunderstood the usage?

**Comment by Addvilz** [comment]
Yes that was in fact my intention.

**Comment by samdark** [comment]
@Addvilz I was thinking about immutability but since there's `prompt()`, ignore it.

**Comment by Addvilz** [comment]
Then perhaps InputInterface is not the best place for prompts and they should have a separate one? Wdyt?

**Comment by Addvilz** [comment]
Discussion in Cache PSR gave me an idea - perhaps we could split the InputInterface into InputInterface and InputPromtableInterface that extends InputInterface? Or would that be too ambiguous?

**Comment by samdark** [comment]
@Addvilz prompts are available in most cases so I don't think it makes sense to separate them.

`InputInterface` name seems to be misleading btw. It should be called `CommandLineInputInterface`.

**Comment by Addvilz** [comment]
Quite a long name. Perhaps `CliInputInterface`?

**Comment by geggleto** [comment]
Does symfony console not have this already? Perhaps we should just borrow theres? I love symfony console.

**Comment by TorbenKoehn** [comment]
I'm an for a standardized input- and output interface, but it needs to be _completely_ reusable and not coupled to CLI.

It should work fine coupled with streams, a ReadAndWritableStream should implement both in the best case (they're interfaces, so they don't have to)

Also, we have IDEs and PHP is not Java, so let us take "writeLine", not "writeln". It helps reducing confusion for people just learning PHP.
"writeError" shouldn't even exist as there are too many different kinds of output types/severities, they should rather be abstracted away.

Things like Prompts shouldn't be in the base-interface, thats an implementation detail already.
Keep it short, small and as interop as possible.

**PSR-io**

``` php
interface InputInterface
{

    public function read($length = null);
    public function readLine();
}

interface OutputInterface
{

    public function write($data);
    public function writeLine($data);
}

//Implementors can choose parsing logic for input data and provide options, e.g. Query String, CLI Input Args etc.
interface OptionInputInterface extends InputInterface
{

    public function getOptions();
    public function getOption($name);
    public function setOptions(array $options);
    public function setOption($name, $value);
}
```

Additionally, the following could be added or put into an own PSR (_PSR-cli_)

``` php
interface CliInputInterface extends OptionInputInterface
{

    public function getArguments();
    public function getArgument($index);
    public function setArguments(array $args);
    public function setArgument($index, $value);

    public function isInteractive();
    public function setInteractive($interactive);
}

interface CliOutputInterface extends OutputInterface
{

    public function isDecorated();
    public function setDecorated($decorated);
}
```

Small (dirty) example of a simple Logger based on that

``` php
//Error, Info, Warning etc.
interface LogMessageInterface
{
    public function getSeverity(); //error, warning, info
    public function __toString(); //Message
}

class LogMessage implements LogMessageInterface { /* ... */ }

class Logger
{

    private $output;

    public function __construct(OutputInterface $output)
    {

        $this->output = $output;
    }

    public function log($message)
    {

        if ($message instanceof LogMessageInterface 
            && $this->output instanceof CliOutputInterface 
            && $this->output->isDecorated()) {

            //Apply ANSI-colors etc. based on $message->getSeverity()
        }

        $this->output->write($message);

        return $this;
    }

    public function error($message)
    {

        return $this->log(new LogMessage($message, 'error'))
    }
}
```

PSR/CDS should focus on interfacing, not implementing in my opinion.

**Comment by Addvilz** [comment]
The target for these interfaces is CLI applications. There are enough HTTP IO implementations and interops already covering pretty much every aspect of HTTP transport.

You also have a great example of API hell right there. Please, remember, that target for these interfaces is not something to be able to blog about, but every-day use.  By that, implementations will almost always implement the widest feature set anyway to avoid ambiguity and provide clear and easy to use interface to both CLI input and output. Symfony Input is a great example of that - commands, for example, receive Input and Output, in your case they would receive what exactly? Also, both contain something that is not 100% related to the same thing, but it is a public feature api that is easy to use. There are great many such examples across platforms and frameworks.

Also, the CLI IO has nothing to do with logging. `writeErr` clearly refers to stderr, `write` to stdout. Logging verbosity is logger and application domain, not IO one.

No need to over-engineer this.

**Comment by TorbenKoehn** [comment]
@Addvilz You're specifying CLI interfaces, I am specifying Input and Output interfaces. This is not primarily for the HTTP layer, it rather gives you the possibility to feed applications and classes with input-objects that are not required to originate from the CLI or a HTTP request. The input could even be constructed manually, with an option-array etc.

What my approach tries to do is merging the way you feed your instances with input.

To see what it's trying to aim at, you have to distance yourself from Symfony for a second. I just wrote like 200 lines of text here, I deleted those, I'd rather explain it in code.

``` php
<?php


class UserController
{

    public function viewAction(User $user)
    {

        //Notice that the controller doesn't (and never will) "render" or anything
        //The controller returns data, either scalar or objects and a FrontController
        //will handle "render" (HTML), JSON, XML etc. automatically based on serialization annotations

        //Yes, a viewAction could be as small as this here with the fitting framework

        return $user;
    }
}


$app = new Application();

//...service initialization/whatever...


//Either dispatch from HTTP
//HttpOutput will automatically handle serialization based on a format given as well as template-rendering (implementation-dependant)
$app->dispatch(new HttpInput(), new HttpOutput());

//or from CLI (and have the SAME methods/actions and e.g. an output-formatter, that serializes into ASCII-tables)
//Imagine app.php --route user/view/4
$app->dispatch(new CliInput(), new CliOutput());


//or you rather build your input by yourself
$app->dispatch(new CustomInput(['route' => 'user/view/4']), new MemoryStream());  //The MemoryStream part is pretty important, it implements OutputInterface _and_ InputInterface

```

I agree on the Error-part, I didn't take into account STDERR, but I wouldn't even couple that with the OutputInterface, since with OutputInterface you're basically representing STDOUT and it shouldn't do both. STDERR should rather be an `ErrorOutputInterface` extending `OutputInterface`

``` php
interface ErrorOutputInterface extends OutputInterface
{
}
```

When I think about IO, I apply it on everything. Every method in your code has **Input** and **Output** (Even if the Output is `null`), so why not apply this scheme in a more general way. Application-classes have Input and Output. Streams have Input and Output.

I get that you're a great Symfony-fan and all, I am too!, but I hope this is not a "Let's make all Symfony-components and paradigms the standard" since everyone has their own view of what is a good and dynamic code-base and what not and we should respect that (which is why InputInterface and OutputInterface consist of 4 methods in total)

The difference between our two approaches is just the fact that my version doesn't force you too hard to stick to specific implementations.
You could write a "Stream"-library and just use InputInterface and OutputInterface, which are 4 methods in total, without ever touching any of the other interfaces. But you'd enable your Stream to be set as any application's output and it gets filled correctly.

If this is for CLI only, then please rename this thread to "CLI Input/Output" and we're just not talking about the same thing. I/O is not console in general. IO is IO. Anywhere.

**Comment by Addvilz** [comment]
I can see how the title could be misleading, I changed it. 

I agree with you on the IO point, but that really was not my intention. The issue I have with your proposal is not that it's not Symfony-ish enough, it's that in this particular case I imagined the input and output to be provided by application to X extension, in a similar way how Symfony commands work (yes, I know, I am fanboy :dancer:). But it kind of makes sense if you think of it that way. If you have N interfaces for this, and you still want to inject things like this, how do you choose which interfaces to require and target?

Your version would be perfectly fine if the implementations would be provided by consumer (e.g. guy who develops the app), but how to be when the implementation is provided by framework? That rises some issues.

**Comment by TorbenKoehn** [comment]
Well, the awesome advantage with interfaces is (and always will be) the fact that you can implement many of them at the same time :)

If you know that you need CLI Output functionality, you can always hint for a CliOutputInterface instead of an OutputInterface

Why would it rise issues providing several default implementations in a framework? Maybe you can explain that a bit. You mostly type-hint OutputInterface and InputInterface (The most things you need are `write` and `read` anyways)

Everything else can be solved with decorators (which, in turn, can be applied on everything again)

---

Personally, I'd even rework PSR-7 and put the StreamInterface in an own PSR, making it depend on PSR-io and let it implement OutputInterface and InputInterface by default, but that's just me (and it's too late for that I guess). The "depend" part is bad I guess.

I don't see why that couldn't be the global Stream interface for everything. People could finally mix streams from libraries all over and create simple Input/Output implementations based on 4 methods of which 2 are "Call the other one and add EOL"

---

Maybe we should talk about a general IO interface, too? ;)

**Comment by Addvilz** [comment]
The issue is not providing multiple implementations, or anything like that. The issue is how do you decide which of these implementations will be a default service you expose for consumption. :) Or do you propose creating new instances for each service that requires them. Or creating and providing all instances. Or one huge extended one that still implements all the features. 

That's one of the reasons why having split interfaces in this case simply isn't practical.

**Comment by TorbenKoehn** [comment]
In code

``` php
<?php


$app->set('default-input', function (array $appConfig) use ($app) {


    if ($appConfig['output_class']) {

        $outputClass = $appConfig['output_class'];
        return new $outputClass();
    }

    return $app->isCli() ? new CliOutput() : new HttpOutput();
});


$app->set('default-output', function (array $appConfig) use ($app) {


    if ($appConfig['input_class']) {

        $outputClass = $appConfig['input_class'];
        return new $outputClass();
    }


    return $app->isCli() ? new CliInput() : new HttpInput();
});

//You might even split input_class into cli_input_class and http_input_class and maybe even cli_server_input_class

class App
{

    //...

    function run(InputInterface $input = null, OutputInterface $output = null)
    {

        return $this->dispatch(
            $input ?: $this->get('default-input'),
            $output ?: $this->get('default-output')
        );
    }
}
```

That's just a dirty example, imagine App is a DI or at least a config-container.

The framework itself would have no problems providing some default implementations and still allow the consumer to create own Input/Output implementations.

But the great thing is: You can actually control the input and output of your application completely and easily run different apps with different input/output-types in single batches, merge the results and combine advantages of different apps.

It could allow you to use the `Blog`-controllers of one app somewhere but disallow routing to all other parts inside it, but have another app (maybe even with a completely different framework behind it) be called directly after it, without interferring each other

**Comment by Addvilz** [comment]
Well, your code sample directly illustrates why this probably shouldn't be split in so much small Interfaces. In your `run` method you are still expecting `InputInterface` or `OutputInterface`. So you can either inject those implementations or something that extends those implementations, but not less that that.

Imagine if you have a collection of `App` instances - would you rather have them all equal `run` signature or different ones. And if different ones, and if you have multiple `App` instances (which would constitute, lets say, CLI commands), App itself should be implementation of an `App` interface. As long as you use call-by injection, you can't have different input/output classes injected there as that would break the interface. 

And I can still control the source of input completely. Here is the real life sample (sorry, Symfony again, I just know where to look it up quickly) of similarly implemented interfaces: http://api.symfony.com/2.7/Symfony/Component/Console/Input.html

This would not work with multiple interfaces you propose (interface break).

``` php
interface CommandInterface
{
    public function run(InputInterface $input, OutputInterface $output);
}

class CommandFoo implements CommandInterface
{
    public function run(InputInterface $input, OutputInterface $output) {}
}

class CommandBar implements CommandInterface
{
    public function run(InputInterface $input, OutputInterface $output) {}
}
```

This would:

``` php
interface CommandInterface
{
    public function run();
}

class CommandFoo implements CommandInterface
{
    private $input;
    private $output;

    public function __construct(InputInterface $input, OutputInterface $output)
    {
        $this->input = $input;
        $this->output = $output;
    }

    public function run(){}
}
```

**Comment by TorbenKoehn** [comment]
It really doesn't matter, since you're targeting CLI-input/output here.

My idea was not to have an `AppInterface` (which should _never_ exist since it's a really generic one).

It doesn't matter if you have `run($input, $output)` on your App, `dispatch($input): OutputInterface` on your front controller or `log()` into `OutputInterface` in your logger, `__construct(InputInterface, OutputInterface` on your `CommandInterface` etc., what I am suggesting is a global "Read/Write"-interface which instances can be passed around to almost everything in your application (since most parts of your application work based on Input/Output logic)

If I, as a framework-maintainer, define my App-class to have a method `run` that expects two instances of this PSR, is my thing and I don't expect that one to be interopable. And it doesn't even matter (You usually don't have an array of Apps you call, such things are handled via Middleware. This is more for enterprise-cases and for correct application, input and output encapsulation)

``` php
<?php

$blogApp = Some\Framework\Application::create(['config' => 'blog-config.xml']);

$app = new Other\Framework\App('app-config.yml');


//$blogApp->run(InputInterface $input): OutputInterface $output

//$app->handle(InputInterface $input, OutputInterface $output)


$input = new HttpInput();
$app->handle($input, $blogApp->run($input, $output));
```

What you're doing is encapsulating a Console-library with interfaces. Your console implementation will not be able to run commands based on a HTTP Request's GET-parameters, mine would (`GET /some/command/route?help` could be translated to `some:command --help` easily).

As said, it doesn't matter, we're talking about two different things here and this thread is about Console-abstraction, so I'll keep my overall-general-IO-stuff out of this haha

**Comment by shouze** [comment]
To me we don't need any setter in the input interface... there's many ways to set argument/options/interactive mode once as it won't change. I don't understand why we want to introduce mutability here... we could use a constructor or a named constructor.

About the getters... are we sure we have use cases where we want to get arguments or options? Maybe we just need some toString method to dump the command, no more?

**Comment by Addvilz** [comment]
Mutability is not an evil beast to be avoided at all cost. I don't see the tradeoff here between having an immutable interface and mutable on. On the very least, mutable one allows "middleware" like behavior of adding options down the execution chain. That can be done by decoration... but why?

Not sure about your statement about the getters. I don't see a point of having, basically, an interface towards CLI arguments without ability to get command arguments and options. How would you consume that via toString?

**Comment by Addvilz** [comment]
Withdrawn.
