### ISSUE TITLE
[RFC] Middleware Interface

### ISSUE THREAD

**Issue by geggleto** [php-cds/php-cds#5]
I know there isn't a formal Middleware Interface for PSR-7 projects... Seems like an easy one to start off with.

``` php
interface Middleware {

    public function __invoke(ServerRequestInterface $request, ResponseInterface $response, callable $next);

}
```

**Comment by shadowhand** [comment]
This has already been started by FIG, see php-fig/fig-standards#755.

**Comment by geggleto** [comment]
Yes it has, however as far as I know there is no timeline for it's adoption.

**Comment by samdark** [comment]
@geggleto it's better to focus on something else rather than on things being worked on.

**Comment by TobiasJ** [comment]
I think samdark is right. In order to avoid confusions and to avoid splitting the community in php-fig and php-cds camps / users / lovers there shouldn't be two psrs for the same thing. Maybe someone is able to write down a list with on going php-fig rfcs, so it will be easier for the "not so deep into php-fig rfc" people to figure what could be useful to start with.

**Comment by samdark** [comment]
@TobiasJ the list won't be looked at so I think it's better to leave it as is i.e. FIG-aware people will comment on that before it goes too far.

**Comment by samdark** [comment]
@geggleto this one should be closed, right?
